### ISSUE TITLE
Bug? help pls

### ISSUE THREAD

**Issue by tamihuber** [paulwinterbauer/NBIC#110]
It won't let me send this. This is what comes up when I hit 'send'. 
![image](https://user-images.githubusercontent.com/100441006/164453229-6547e0bb-02da-4f0e-98e3-7ee07ee2603b.png)

**Comment by paulwinterbauer** [comment]
Do you still want to send this?  It's marked as DQ now

Usually re-review will fix these types of errors.

**Comment by tamihuber** [comment]
I do want to send. I'll re-review. thanks!
