### ISSUE TITLE
No response to go out for where numTIB is the only response.

### ISSUE THREAD

**Issue by tamihuber** [paulwinterbauer/NBIC#140]
AND where TBOB > 0, Num TIB = 0 value err exists as well.
Ex. https://review.ballastreport.org/NBIC/review/2845641/

**Comment by paulwinterbauer** [comment]
NumTIB was manually flagged on that one. why not have them not do that?

**Comment by tamihuber** [comment]
Because when there's more than one flag (for response) that is going out, they should flag that as well. Is it possible to have these reports categorized (flag-wise) for when certain flags for response (envelopes) are the only ones on a report, that they then don't end up going to the responder (unless there are comments or manual notes)? I'm not going to say the DMs need to know which flags (non-envelopes) they need to flag for and which they don't. That's a bit tedious and inefficient, I would think. I'd think the system could learn which flags we want to send, and which we don't. Is that possible?  Your system is powerful and we shouldn't have to decide ourselves whether our flags mean something or not. The system is capable of that, isn't it?

**Comment by paulwinterbauer** [comment]
Dup of #130
