### ISSUE TITLE
more than one manual response is allowed in system

### ISSUE THREAD

**Issue by tamihuber** [paulwinterbauer/NBIC#158]
We don't want to be able to send more than one, but unless I take specific note that a form had a response already sent out, another WILL go out because the sys allows for it. 

http://serc4.si.edu:8001/NBIC/review/2850363/ is an example, the response already went out before today, but it's allowing another and doesn't show the original post response in the post-response field.

**Comment by paulwinterbauer** [comment]
Moving to #162
