### ISSUE TITLE
finding forms which aren't coming to the Responder but are flagged

### ISSUE THREAD

**Issue by tamihuber** [paulwinterbauer/NBIC#164]
What's the best way to find ones like this below?  In the database, which tables/fields would yield the list? Since they're not coming to the Responder, I worry I've missed many that need responses (or at least which need a scan to ensure nothing is needed). 

https://review.ballastreport.org/NBIC/review/2850761/

![image](https://user-images.githubusercontent.com/100441006/176183930-d1662f41-2799-4065-948e-41436381a793.png)

**Comment by paulwinterbauer** [comment]
It looks like people are going into old/reviewed forms and adding flags.  They would need to hit pause/unpause to trigger the review process to bring up the response.

**Comment by tamihuber** [comment]
THat's new, tho, right? That never had to happen for a form (within a week or 2 of being reviewed) before.

**Comment by tamihuber** [comment]
I just did this to 2786490 -- i added a comment (not a man response note), and changed volumes and flagged them. A response came up. It didn't make it just 'flagged' without a response. Is this different than what you mentioned above?

**Comment by paulwinterbauer** [comment]
Yeah, the difference is you changed volumes.  When you save a field like that it also triggers the review.

**Comment by tamihuber** [comment]
I'm sure you can imagine me scratching my head on this. Do you have a list of changes that does and does not trigger needing to hit pause/unpause? On the original one above, the evvent type and the volume were flagged but no response.

**Comment by paulwinterbauer** [comment]
yes, I'm sure it's head scratching.  Basically adding a comment or a flag does not trigger the review to run.  Anything else that changes data on the report will trigger it.  This going back to old reports to add flags is relatively new behavior, I can see about having the flag also trigger the review, but the next update is a little ways off.

**Comment by tamihuber** [comment]
oh, I see. So only CHANGING data will put it in the responder. I swear I've never had this issue, with reports where they've only flagged for gundecking/etc. Does this mean there are a bunch that haven't come to responses, not only in the past few wks? Is there a good way to query for them? Is saying 'if you don't see a response when you have flagged anything, hit pause and unpause until you do' enough to handle future issues?

**Comment by paulwinterbauer** [comment]
Yes, that will be enough for future ones.

It's complicated depending on how many potential flags they may have applied.  But here's a query that will get ones that got an event type, event volume, or event date flag (received this month, don't know how far you'd want to go back but you can alter that):

Select r.*
From reports r Inner Join report_flags rf On r.ReportID = rf.report_id
Left Join responses resp On r.ReportID = resp.report_id and resp.type in ('post_review', 'manual')
Where r.Status = 'reviewed' and r.Response_Type = 'AutoConfirmation'
and r.TimeReceived >= '2022-06-01 00:00:00'
and resp.id is null
and rf.applied is true 
and rf.flag_category = 'error'
and rf.flag in ('et', 'evol', 'ed')
Group By r.ReportID;
