### ISSUE TITLE
non US disch tanks getting flags/errors

### ISSUE THREAD

**Issue by tamihuber** [paulwinterbauer/NBIC#171]
I thought tanks with no US discharge wouldn't get error responses. The discharge location errors are for tanks without discharge, exc tk 14.

https://review.ballastreport.org/NBIC/review/2856702/

**Comment by paulwinterbauer** [comment]
looks like they were manually applied

**Comment by tamihuber** [comment]
is it possible to have it so even if manual, for non-us discharged tanks (any of the discharge, secondary/etc), the error doesn't go out? I believe it was a multiple-tank location review that got flagged, because the program brings up all tanks. The flag should (in those cases) not apply to non-us discharged tanks.

**Comment by paulwinterbauer** [comment]
You can toggle them in the responder.  It's not a good idea to override manually applied flags.
