### ISSUE TITLE
Non_US waters arrivals

### ISSUE THREAD

**Issue by tamihuber** [paulwinterbauer/NBIC#188]
Would it be ok to not have a response error for non-US waters arrivals for anything like arrival information (except arrival location flagged -- because we may have standardized it to non-US when it's actually US) or events in tanks when the tank's ONLY discharge is to non-US locations?

https://review.ballastreport.org/NBIC/review/2867363/

Just wondering what the system can do to minimize what comes to the Responder automatically.

**Comment by paulwinterbauer** [comment]
see #431
