### ISSUE TITLE
event order review - OBTS same as source or ER

### ISSUE THREAD

**Issue by tamihuber** [paulwinterbauer/NBIC#198]
Is it possible the event order only comes up when event information isn't duplicated (as on https://review.ballastreport.org/NBIC/review/2874725/, where the source and obts info is identical for each source)?

**Comment by paulwinterbauer** [comment]
2872419

**Comment by paulwinterbauer** [comment]
2956141
After he changed the date, the system left tank 17 ordered incorrectly and Event Order review didn’t come up. Is it possible to make that come up when data are standardized (again or for the first time)?
