### ISSUE TITLE
Prblem hand entry

### ISSUE THREAD

**Issue by tamihuber** [paulwinterbauer/NBIC#214]
Was there a bug with this one? opening the pdf shows the data, but it's not in the reviewer. It's on HOLD. is it possible to load the data?

https://review.ballastreport.org/NBIC/review/2883747/

**Comment by paulwinterbauer** [comment]
You should send these to Karl so he can investigate what happened with the parsing.  Then just use the 'Move to Hand Entry' option in the Actions menu.

**Comment by tamihuber** [comment]
@karlsi Let me know when I should "move to hand entry"! Thanks

**Comment by paulwinterbauer** [comment]
There's no need to wait, he can check the file out regardless.

**Comment by karlsi** [comment]
Data fields cannot be read from the PDF.  Probably used a non-conforming PDF reader.
