### ISSUE TITLE
disch>source issue?

### ISSUE THREAD

**Issue by tamihuber** [paulwinterbauer/NBIC#222]
Why is tk 2 disch>source coming up (but tk 1 isn't)? The FT is more than 3x the total sources on both tanks.

https://review.ballastreport.org/NBIC/review/2884528/

**Comment by paulwinterbauer** [comment]
The discharge volume was greater than the capacity.

**Comment by tamihuber** [comment]
why is the disch>source error coming up tho? Don't we have a "disch exceeds capacity" error?

**Comment by paulwinterbauer** [comment]
The press up calculation doesn't happen when the tank goes over capacity, but it wasn't far enough over capacity to trigger the disch exceeds capacity error.

**Comment by tamihuber** [comment]
How should I handle this?

**Comment by paulwinterbauer** [comment]
I just took .1 off the disch vol and the press up applied.

**Comment by tamihuber** [comment]
THanks!
