### ISSUE TITLE
Tank Name review module

### ISSUE THREAD

**Issue by tamihuber** [paulwinterbauer/NBIC#248]
is it possible to have us only review tanks that list US discharge?

**Comment by paulwinterbauer** [comment]
No, because it's factored into combining tanks as well.  The part B tank block could not have discharge.

It doesn't check any tanks though if there is no discharge on the report.

**Comment by tamihuber** [comment]
I've seen several where there was no US disch on the report (or any disch for that matter, all disch vols =0) and it still came up. That was what I meant to be asking--- that if a report doesn't have discharge, could we not have it come up. I didn't phrase it correctly in the issue.

**Comment by paulwinterbauer** [comment]
It's not limited to US discharge, but there should be discharge on the report.  Send me a report ID if you see it again

**Comment by tamihuber** [comment]
WIll do. It comes up often actually.

**Comment by tamihuber** [comment]
You're right, it's coming up when any discharge is listed-- but could we narrow it down to any discharge, but only when there IS US discharge on the form?
