### ISSUE TITLE
Port Aliases from the web app

### ISSUE THREAD

**Issue by tamihuber** [paulwinterbauer/NBIC#249]
Can you provide again the insight/info as to how ports are aliased on the web app entries? THanks!

2891610 - Bermuda (Bermuda) is aliased, but it's not in the port_alias table in BE.

**Comment by paulwinterbauer** [comment]
When we created the locations table for the web app db we copied certain ports from the NBIC_BE.locations table.  Then we linked them by assigning the web app id in NBIC_BE.locations.wa_id.  This is not an alias per se, it's literally that they selected this port.

**Comment by tamihuber** [comment]
Is it possible to remove those from the web app table or remove the link? Bermuda (Bermuda) is not a port, for instance. They came to Hamilton.

**Comment by paulwinterbauer** [comment]
Yeah, we can null the wa_id field.  I'll take care of this one.

**Comment by tamihuber** [comment]
Thanks!

**Comment by tamihuber** [comment]
I don't know how many others are like this in the wa....is it possible to remove any generic locations like that one?

**Comment by paulwinterbauer** [comment]
Mark vetted/approved everything that we added to the web app db.  So wouldn't think there would be many, but you could query the locations table for wa_id is not null if you want to check.

**Comment by tamihuber** [comment]
Thanks! I'll do that!
