### ISSUE TITLE
qc location review request

### ISSUE THREAD

**Issue by tamihuber** [paulwinterbauer/NBIC#269]
Would it be possible (even tho it's a location review) to show the DATE that is associated with the location being reviewed? Not sure if it would ever show a location that occurs on more than one tank which has more than one date also (obviously that would cause issues with what I'm requesting then), but if not, could it show the date? It would help for looking at the map and not needing to scroll down and up to the tanks and map every time. 

![image](https://user-images.githubusercontent.com/100441006/196691360-30c1de7f-c7ec-4cc8-b85f-8283bc4e9fac.png)

**Comment by paulwinterbauer** [comment]
#465
