### ISSUE TITLE
Transfer to and transfer from Event type options and location options

### ISSUE THREAD

**Issue by tamihuber** [paulwinterbauer/NBIC#271]
Not sure how difficult this would be, but could this be a priority? Having at least the event type options would be priority. I'm not sure if we should have a 'transfer to' and 'transfer from' location option as well -- not sure we need it if the event types exist, but I imagine there could be some instances where we need to leave the event types as is and use the location field for the transfer bit.

**Comment by paulwinterbauer** [comment]
#88
