### ISSUE TITLE
mark review issue

### ISSUE THREAD

**Issue by tamihuber** [paulwinterbauer/NBIC#282]
https://review.ballastreport.org/NBIC/review/2899387/
Ashley had originally reviewed this, and then I wanted to see what came up during review, and when I went to Mark Review Issue, it doesn't give me AA initials. Could we either capture all reviewers (regardless of hitting re-review), or allow any DM's initials to be selected (this is obviously not a great option)?
I now can't send it back to Ashley.

**Comment by paulwinterbauer** [comment]
#261
