### ISSUE TITLE
Reviewer request

### ISSUE THREAD

**Issue by tamihuber** [paulwinterbauer/NBIC#290]
Since ships often list US discharge as secondary or primary (or other), is it possible to highlight any US discharge events (Maybe just highlight the event type?) in a purple or yellow color (or whatever color you suggest)? It's a pain to look at lat longs that may or may not be US discharge (within 12nm), and is a bit of a time sink. Since the US tally doesn't tally older than primary,  it would help us know when we need to check older forms for updates/gundeck/conflicts for those tanks. 

Thanks!

**Comment by paulwinterbauer** [comment]
see #275
