### ISSUE TITLE
NVMC lpoc showing "chained port" on vessel history page

### ISSUE THREAD

**Issue by tamihuber** [paulwinterbauer/NBIC#30]
Not sure if it's only particular years, but 2018 isn't showing "chained" like I've seen on other years. Not sure the screenshot is working-- I'm trying to screenshot 3297712 (NVMC).
![image](https://user-images.githubusercontent.com/100441006/156409713-2c01fb71-0448-4c04-aba8-2d937d336a71.png)

**Comment by paulwinterbauer** [comment]
Updated v3.0
