### ISSUE TITLE
tk capacity difference - missing from history

### ISSUE THREAD

**Issue by tamihuber** [paulwinterbauer/NBIC#303]
not sure why the one in red circle isn't on the reporting history on the left?

![image](https://user-images.githubusercontent.com/100441006/205669202-10fbe47f-98e0-45d9-965e-065e445d301e.png)

**Comment by paulwinterbauer** [comment]
It's a relic of the earlier UI I was building, the paragraph above the table explains it.  In any case, I'm making it a full history again in the next update.
