### ISSUE TITLE
BIG PROBLEM- reason no mgt bug?

### ISSUE THREAD

**Issue by tamihuber** [paulwinterbauer/NBIC#304]
http://serc-cg01.si.edu:8001/NBIC/review/2913750/
I had to manually flag reason no mgt. Otherwise, no errors were shown for this report. Am I missing something? SHould it not be an error (it's early, so maybe my eyes aren't seeing something obvious)?

**Comment by paulwinterbauer** [comment]
When I reviewed it, reason no mgmt review came up.

**Comment by tamihuber** [comment]
review came up, the flags didn't.

**Comment by paulwinterbauer** [comment]
Ah, it's because of the ALT instructions via COTP
