### ISSUE TITLE
reason no mgt issue- different slightly

### ISSUE THREAD

**Issue by tamihuber** [paulwinterbauer/NBIC#305]
http://serc-cg01.si.edu:8001/NBIC/review/2914070/
why isn't tk 13 getting same error

**Comment by paulwinterbauer** [comment]
It comes down to how we define a press up, since we try to exclude press ups from these errors.  The criteria we're using considers tank 13 to have a press up but not tank 12.

**Comment by tamihuber** [comment]
Is it possible to exclude any report from the responder when the ONLY error is Reason no mgt if the unmanaged sources without a reason are >200nm outside land?

**Comment by paulwinterbauer** [comment]
Is there any reason to keep those flagged in other circumstances?

**Comment by tamihuber** [comment]
yes, when there are other reason no mgt criteria (so, when it's within 200nm, etc) on the report, we want the Reason error to go out for every tank that doesn't have a reason.
