### ISSUE TITLE
Non-US discharge on reports rendering responses -- bug?

### ISSUE THREAD

**Issue by tamihuber** [paulwinterbauer/NBIC#308]
http://serc-cg01.si.edu:8001/NBIC/review/2916570/
I thought you made it so only reports with US discharge come to the responder?

**Comment by tamihuber** [comment]
Also, where the arrival is non-US 12nm (and no US discharge), is it possible to not have it go to Responder? 
http://serc-cg01.si.edu:8001/NBIC/review/2916941/

**Comment by tamihuber** [comment]
https://review.ballastreport.org/NBIC/review/2917581/ too.

**Comment by paulwinterbauer** [comment]
We've modified some flags to not apply when there is no US discharge, but not to the degree you're suggesting.  What about arrivals without tanks, but the treatment system/arrival date/whatever get's flagged, would you not want to send response?

**Comment by tamihuber** [comment]
I wonder if the only time a response comes to the responder for non-US arrivals is for flagged arrival and/or discharge locations. OBTS, arrival date, or any other page 1 info flagged for non-US arrival locations --> no response. On the other hand, if the arrival location (non-US) and/or discharge (non-US) locations are flagged --> go to Responder. Thoughts?
