### ISSUE TITLE
Wording for response for "Multiple Tanks value err"

### ISSUE THREAD

**Issue by tamihuber** [paulwinterbauer/NBIC#314]
The reported TANK information (Tank Name/Number) could not be verified for the following tanks (tanks numbered by order in report):

      •	Enter tanks as single listings, not as paired or multiple tanks in one tank block. Each tank block refers to one tank only.

**Comment by paulwinterbauer** [comment]
#476

**Comment by paulwinterbauer** [comment]
#554
