### ISSUE TITLE
add a date format to the algorithm

### ISSUE THREAD

**Issue by tamihuber** [paulwinterbauer/NBIC#348]
is it possible to include these characters in  date algorithm to have them auto standardized? Or at least so the date will come up in the search box for what it probably is?

![image](https://user-images.githubusercontent.com/100441006/210830027-406f4c9c-5dd0-40c1-8000-489dc5e9678a.png)

**Comment by paulwinterbauer** [comment]
In the future, it's really important to provide the report ID.  I'll try to track this one down...

**Comment by paulwinterbauer** [comment]
2923544

**Comment by tamihuber** [comment]
OMG! I can't believe I forgot-- I bet I forgot to hit Paste. Sorry about that. Hopefully you know that's ingrained in my brain ;) (to give you a report ID). So sorry you had to go searching for it.

**Comment by tamihuber** [comment]
https://review.ballastreport.org/NBIC/review/2924437/ too :)
