### ISSUE TITLE
criteria for when OBTS needs to be standardized?

### ISSUE THREAD

**Issue by tamihuber** [paulwinterbauer/NBIC#353]
We had a question-- on report 2925445, the OBTS review came up, but it's been standardized over 10 times and the raw is exactly the same every time. Do we need to standardize every time? Now, I will also say that when we hit re-review, it didn't come up for obts review. So did we hit the criteria number that it needed just then? I can't imagine we did, but maybe?

**Comment by paulwinterbauer** [comment]
see #363
