### ISSUE TITLE
Add indicator to Tank display for discharge status

### ISSUE THREAD

**Issue by tamihuber** [paulwinterbauer/NBIC#37]
http://serc4.si.edu:8001/NBIC/review/2816041/
The source volume (reported=null) needed to be flagged to come up in the flagged responses. If this is new (as I think it is), and if this is happening with all forms (not just maybe this one), this is a big problem because folks likely won't flag null reported volumes (since it used to automatically occur). Please help.

**Comment by paulwinterbauer** [comment]
Updated v3.0
