### ISSUE TITLE
Review Issue - allow any initials to be selected to send the report to

### ISSUE THREAD

**Issue by tamihuber** [paulwinterbauer/NBIC#374]
Esp due to training, it would be helpful to be able to choose any of the DMs to send a report back to (including my initials). There are sometimes comments made by a person too, where they didn't necessarily do an action (amendment, re-review, changes to form, initial review), and I'm not sure if they would come up for just a comment either. Overall, though, having the ability to choose any of the initials would be extremely helpful.

**Comment by paulwinterbauer** [comment]
#261
