### ISSUE TITLE
Source locations getting start point errors- Bug?

### ISSUE THREAD

**Issue by tamihuber** [paulwinterbauer/NBIC#379]
Why is the response coming up for the location issue? Shouldn't be mgt start and end pts in the response (2nd screenshot below). https://review.ballastreport.org/NBIC/review/2929571/

![image](https://user-images.githubusercontent.com/100441006/214320761-52813131-b7af-43ca-9c9b-8cb54ee909c1.png)

![image](https://user-images.githubusercontent.com/100441006/214321002-19b97224-7575-408b-b32a-35efe0c71d68.png)

**Comment by paulwinterbauer** [comment]
#487
