### ISSUE TITLE
BUG? https://review.ballastreport.org/NBIC/review/2929883/

### ISSUE THREAD

**Issue by tamihuber** [paulwinterbauer/NBIC#380]
why is disch>source coming up for this?
![image](https://user-images.githubusercontent.com/100441006/214344951-f244c78c-e2cd-4a0b-a3e7-d28757790e15.png)

**Comment by paulwinterbauer** [comment]
The ER plus source after puts the tank over capacity, which is preventing the press up from being added.

**Comment by tamihuber** [comment]
Is it possible to not have this flag come up when this happens since it's wrong (the discharge isn't greater than the source here)? The one for exceeds capacity is there and is correct, but we shouldn't have disch>source unless I'm missing something.
