### ISSUE TITLE
HELP: Please check and update ASAP

### ISSUE THREAD

**Issue by tamihuber** [paulwinterbauer/NBIC#383]
It looks like when a DM clicks on "Mark for Manual Response" in the Action menu, the web app forms DO NOT come to the Responder, even though when *I* click that and leave a comment, it does. I need all of them to come to the Responder. 

Please help. This is only one of a few I've already found this morning. 

https://review.ballastreport.org/NBIC/review/2894644/#

**Comment by paulwinterbauer** [comment]
I'm not able to reproduce this.  I've gone through the code and there is nothing related to which user is marking it for response.  Can you have someone do another test?

**Comment by tamihuber** [comment]
yep!
