### ISSUE TITLE
have tank vol below 0 flag only show unique tanks

### ISSUE THREAD

**Issue by tamihuber** [paulwinterbauer/NBIC#448]
INstead of showing 3 (example below), could it just show tank 5 (so, 1 tk flag only)?
https://review.ballastreport.org/NBIC/review/2951981/

**Comment by paulwinterbauer** [comment]
It's an event level flag.  I'm not sure if we need it anyway?

**Comment by tamihuber** [comment]
Each DM reviews the tk vol below 0 in case the report warrants a flag that isn't on the report in relation to that flag. Lots of times the disch> source flag handles it, but sometimes it doesn't, and they need to flag something (guessing we need to find those reports, so we can better assign flags). What's your thinking that we wouldn't maybe need it?

**Comment by paulwinterbauer** [comment]
No real reason, it's just not a response flag.
