### ISSUE TITLE
Bug? Reason no mgt not coming up

### ISSUE THREAD

**Issue by tamihuber** [paulwinterbauer/NBIC#450]
It looks like it's the end of the ER anyway (so we need to combine the ER and source events), but without combining, why isn't reason no mgt coming up for that second source? Seems to have come up on the prior submission for this arrival. 

http://serc-cg01.si.edu:8001/NBIC/review/2951931/

**Comment by paulwinterbauer** [comment]
They're press ups.  The previous form had another source 3 days after the exchange that triggered the reason no mgmt.

**Comment by tamihuber** [comment]
What is the time/day criteria for triggering reason no mgt (is it 3 days or more?)?

**Comment by paulwinterbauer** [comment]
These latlon sources are treated as press ups if within a day of mgmt
