### ISSUE TITLE
NVMC canceled records - hitting YES voids the left-sided NOA record

### ISSUE THREAD

**Issue by tamihuber** [paulwinterbauer/NBIC#453]
Would it be possible to have a prompt come up asking "do you want to void the left report"?  This is confusing (without a prompt) for the DMs needing to remember that is what happens when you click "yes" when comparing 2 NVMC (where the one on the right is a 'cancelled' (red) record).

**Comment by paulwinterbauer** [comment]
This is by design, the left report is the earlier report, if the one on the right is cancelled that would mean the arrival is cancelled.

**Comment by paulwinterbauer** [comment]
Actually, this looks like a bug alright!  Sorry!

**Comment by tamihuber** [comment]
Great. No worries.
