### ISSUE TITLE
Show tank events distinctly identifiable on map

### ISSUE THREAD

**Issue by tamihuber** [paulwinterbauer/NBIC#57]
![Capture](https://user-images.githubusercontent.com/100441006/158192449-17c07291-524a-40f9-b056-7cbf7c26449d.JPG)

all events on same date are the same event type.
http://serc4.si.edu:8001/NBIC/review/2818563/

**Comment by paulwinterbauer** [comment]
I'm pretty confused about what you're asking here.  Can you elaborate a bit?

**Comment by tamihuber** [comment]
since they're all discharges (thus, blue dots), it's impossible to see which dot is which. Could the dots maybe have the event order number IN the dot? so when we zoom in, we can see which event we're looking at?
