### ISSUE TITLE
Reason no mgt for actual midocean only sources

### ISSUE THREAD

**Issue by tamihuber** [paulwinterbauer/NBIC#58]
http://serc4.si.edu:8001/NBIC/review/2818871/

We don't need to send these responses, per MM. Since they're >200nm offshore. I thought we had this in the system already, but when the only error for reason no mgt applies to a tank that has ONLY actual mid-ocean sources, no response flag needed. When there is more than one tank with reason no mgt errors, and they're not mid-ocean, then ALL (including the mid-ocean tanks) tanks should get a response flag. Is this possible?

**Comment by paulwinterbauer** [comment]
I would really prefer if errors were independent/not contingent on other errors being present.  Can we just remove these as errors without considering if other reason no mgmt errors are there?

**Comment by tamihuber** [comment]
Unfortunately we can't, because since vessels are using possibly different spatial coordinate calculations for 'outside 200nm', etc., when we send a report a response for reason no mgt for 11 of their 12 tanks because of our distance calculations, and that one last tank is very close to the other, but doesn't register as within 200nm, it looks confusing. We had that originally, and it was causing an issue along the line of responses. That's why I had you add it back in, but no worries. We'll leave it in. I'm just trying to make things easier on the DMs when they go to be responding. the less to respond about, the easier ;)!
