### ISSUE TITLE
Add way to Remove a flag

### ISSUE THREAD

**Issue by tamihuber** [paulwinterbauer/NBIC#60]
does that initial flagging show up in the db (even tho it's unchecked ultimately)?

**Comment by paulwinterbauer** [comment]
Yes.  There will still be a record in the report_flags table, what happens is there's a True/False field called 'applied' that would be set to false.

**Comment by tamihuber** [comment]
So, this would be longer term probably, but in the sense of tracking what events we've flagged but then unchecked (for relevancy (or lack of) on the report or another issue), to track how well vessels do at filling out the form, i wonder if it's possible to have some way to completely remove a flag from a report's history. When someone flags something accidentally, and doesn't at all mean to flag an issue. I know your 'false' applied field is likely to mean that flag doesn't apply to the report, but in my thinking, the false just means that we didn't want to apply that error to the response, but it still applied to the report.  If that's something you'd like to discuss further, I'm happy to.

**Comment by paulwinterbauer** [comment]
Sure, I could add a way to remove a manually applied flag.

**Comment by tamihuber** [comment]
Cool!
