### ISSUE TITLE
obts is out of service

### ISSUE THREAD

**Issue by tamihuber** [paulwinterbauer/NBIC#66]
http://serc4.si.edu:8001/NBIC/review/2820266/
would be great to have a flag of some sort to check so that the response doesn't go out for the obts field.

**Comment by paulwinterbauer** [comment]
Might be missing your point, isn't that already possible (unchecking the obts error flag)?

**Comment by tamihuber** [comment]
Ha! You're right, I didn't explain my point very well. Instead of adding another 'hey you need to remember this' line in the protocol, where people need to actively remember something like 'when they put it's out of service, you unflag', I was hoping that on the OBTS review module there would not only be the 'standardize the system' part, but a checkbox that is for 'obts out of service', that folks would check/flag so a response wouldn't be generated. This might also (might) be useful to CG, where they could see how many ships and in how many instances a system is reported as not in service.  Sorry for the confusion.

**Comment by paulwinterbauer** [comment]
Ah ok, that makes sense.

**Comment by tamihuber** [comment]
Thank goodness! I can't believe it DID! ha.
