### ISSUE TITLE
report ID order within a single arrival on vessel history page

### ISSUE THREAD

**Issue by tamihuber** [paulwinterbauer/NBIC#70]
why isn't the order of reports in order from highest to lowest report ID within an arrival (all the Mar 18 ones)? Could that be done?
![Capture](https://user-images.githubusercontent.com/100441006/159911787-c44851a0-e385-4211-8bae-abf8391d2cfe.JPG)

**Comment by paulwinterbauer** [comment]
I imagine it's because of the matched nvmc record, do you have the vessel id handy?  I do think I could add alternate sorts to the page..

**Comment by tamihuber** [comment]
another example:
![image](https://user-images.githubusercontent.com/100441006/161829025-3cb0a6eb-eeef-4ec5-b6c5-fea99a9910ec.png)

**Comment by paulwinterbauer** [comment]
dup of #136
