### ISSUE TITLE
Remove overlapping year records in vessel history

### ISSUE THREAD

**Issue by tamihuber** [paulwinterbauer/NBIC#72]
http://serc4.si.edu:8001/NVMC/vessel/9403891/HistoryQC/#

 in the 2021 tab, it shows Jan 2022 arrivals, and in 2020, it shows 2021 arrivals. You added the 'load previous year' button. Could the years' tabs only show the arrivals for that year now that the button has been added? Makes the tally for matching more correct and not confusing at all.

**Comment by paulwinterbauer** [comment]
With the load more records function, having overlapping records from previous year is not necessary.
