### ISSUE TITLE
Response wording when all volume errors are for only BWE events

### ISSUE THREAD

**Issue by tamihuber** [paulwinterbauer/NBIC#74]
http://serc4.si.edu:8001/NBIC/review/2822484/

apply the sub text (after the error itself):

     How to report a mid-ocean exchange event: On one event line only, enter the latitude and longitude of both the start point and end point, separated by a "/". Enter the endpoint date. Enter the full volume of ballast water that is pumped and/or gravitated INTO the tank during "Empty-refill exchange", "Flow-through exchange" or "Salt Water Flush". Combination events (+ Treatment) share the same volume. Where the volume of events (+ Treatment) differ, report as solitary events instead.

     * From 33 CFR 151.2005:

      Exchange means to replace the water in a ballast tank using one of the following methods:

     (A) Flow-through exchange means to flush out ballast water by pumping in mid-ocean water at the bottom of the tank and continuously overflowing the tank from the top until three full volumes of water have been changed to minimize the number of original organisms remaining in the tank.

     (B) Empty/refill exchange means to pump out the ballast water taken on in ports, estuarine, or territorial waters until the pump(s) lose suction, then refill the ballast tank(s) with mid-ocean water.

**Comment by paulwinterbauer** [comment]
adding to #26
