### ISSUE TITLE
fix nvmc record autostandardization

### ISSUE THREAD

**Issue by tamihuber** [paulwinterbauer/NBIC#78]
http://serc4.si.edu:8001/NVMC/review/3702927/
Got standardized automatically to Westwego-- not sure why.  Can we fix all of these to Houston?
![image](https://user-images.githubusercontent.com/100441006/160426329-f3a9c46f-886c-4b56-905b-c9ef42df8617.png)

**Comment by paulwinterbauer** [comment]
Complete, modified 11 records.
