### ISSUE TITLE
Source PW events/locations

### ISSUE THREAD

**Issue by tamihuber** [paulwinterbauer/NBIC#98]
When there is a Source PW event (only on tanks with US bw discharge), could there be a 'location and event type qc review' when that location is non-US (location is  NOT betwn 0 and 12nm of shore)?  Actually, I'm not sure there even needs to be a check for this-- perhaps we only need any Source PW events to be flagged for tanks where there is no other BWM reported for that source of water. Is that possible?
Right now, Source PW event type review comes up, but I think it is overall should be something the program should handle.

**Comment by paulwinterbauer** [comment]
Merging with issue #10
